### ISSUE TITLE
Module missing from the PowerShell Gallery

### ISSUE THREAD

**Issue by chriswahl** [rubrikinc/rubrik-module-for-poshbot#13]
## Expected Behavior
Find Poshbot plugin on the PowerShell Gallery as `Poshbot.Rubrik`

## Current Behavior
It's not there 😄 

## Possible Solution
Add it manually to begin, and then ensure that new releases are uploaded to the gallery after undergoing unit testing.

**Comment by chriswahl** [comment]
Published the 0.1.0 version here - https://www.powershellgallery.com/packages/PoshBot.Rubrik/

**Comment by jaapbrasser** [comment]
Published 1.0.0.0
